site_name: THOR
site_description: Transient Hunter for Optimised Ranking
site_author: Fabio Ragosta
site_url: https://fabioragosta.github.io/THOR/

repo_name: FabioRagosta/THOR
repo_url: https://github.com/FabioRagosta/THOR

theme:
  name: material
  language: en

  palette:
    scheme: default
    primary: indigo
    accent: blue
    
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.expand
    - search.highlight
    - search.suggest
    - content.code.copy

markdown_extensions:
  - admonition
  - tables
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Home: index.md
  - Installation: installation.md
  - Quick Start: quickstart.md
  - Tutorials:
      - Tutorial 1: Tutorials/01_thor_data_model_and_pipeline.ipynb
      - Tutorial 2: Tutorials/02_thor_broker_workflow.ipynb
      - Tutorial 3: Tutorials/03_thor_search_all_fusion.ipynb
  - User Guide: user_guide.md
  - API Reference: api.md
  
